# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04f0669f761316ef829da8cfdaa529f7e03b06b22bd137fa425a99751bc2319da4ff24bad9c7d8e5f543bfc9603a2703c33a45ce894e341523c800808059c8aa

test:
  secret_key_base: e712386a3347680a4c99a4cc514395f664102c36e944810552687fb2d72a40200944d89351be72a185edd44eba88cf9a242e6ff1b83106d05bbe97a97fe6ba7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
